name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Set up cross-compilation targets
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Build binaries
        run: |
          mkdir dist
          GOOS=linux   GOARCH=amd64 go build -o dist/modbusbrowser-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o dist/modbusbrowser-windows-amd64.exe
          GOOS=darwin  GOARCH=amd64 go build -o dist/modbusbrowser-darwin-amd64
          zip -j dist/modbusbrowser-linux-amd64.zip dist/modbusbrowser-linux-amd64
          zip -j dist/modbusbrowser-windows-amd64.zip dist/modbusbrowser-windows-amd64.exe
          zip -j dist/modbusbrowser-darwin-amd64.zip dist/modbusbrowser-darwin-amd64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/modbusbrowser-linux-amd64.zip
            dist/modbusbrowser-windows-amd64.zip
            dist/modbusbrowser-darwin-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
